config_paths:
  - resources_servers/bfcl_v4_ast/configs/bfcl_v4_ast.yaml
  - responses_api_agents/bfcl_v4_ast_agent/configs/bfcl_v4_ast_agent.yaml

bfcl_v4_ast_benchmark_agent:
  _inherit_from: bfcl_v4_ast_agent
  responses_api_agents:
    bfcl_v4_ast_agent:
      datasets:
      - name: bfcl_v4_ast
        type: benchmark
        jsonl_fpath: benchmarks/bfcl_v4_ast/data/bfcl_v4_ast_benchmark.jsonl
        prompt_config: null
        prepare_script: benchmarks/bfcl_v4_ast/prepare.py
        license: Apache 2.0
