bfcl_v4_ast_agent:
  responses_api_agents:
    bfcl_v4_ast_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: bfcl_v4_ast
      model_server:
        type: responses_api_models
        name: policy_model
      model_handler: Qwen/Qwen3-8B-FC
      datasets:
      - name: example
        type: example
        jsonl_fpath: resources_servers/bfcl_v4_ast/data/example.jsonl
        license: Apache 2.0
